version: "3"

networks:
  emqx-net:
    driver: ${NETWORKS_DRIVER}

services:
  # EMQX
  emqx1:
    image: emqx/emqx:${EMQX_VERSION}
    restart: always
    environment:
      - EMQX_NAME=emqx
      - EMQX_HOST=node1.emqx.iot
      - EMQX_CLUSTER__DISCOVERY=static
      - EMQX_CLUSTER__STATIC__SEEDS=emqx@node1.emqx.iot,emqx@node2.emqx.iot,emqx@node3.emqx.iot,emqx@node4.emqx.iot
      - EMQX_LISTENER__TCP__INTERNAL=0.0.0.0:11883
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx_ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    networks:
      emqx-net:
        aliases:
          - node1.emqx.iot
  emqx2:
    image: emqx/emqx:${EMQX_VERSION}
    restart: always
    environment:
      - EMQX_NAME=emqx
      - EMQX_HOST=node2.emqx.iot
      - EMQX_CLUSTER__DISCOVERY=static
      - EMQX_CLUSTER__STATIC__SEEDS=emqx@node1.emqx.iot,emqx@node2.emqx.iot,emqx@node3.emqx.iot,emqx@node4.emqx.iot
      - EMQX_LISTENER__TCP__INTERNAL=0.0.0.0:11883
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx_ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    networks:
      emqx-net:
        aliases:
          - node2.emqx.iot
  emqx3:
    image: emqx/emqx:${EMQX_VERSION}
    restart: always
    environment:
      - EMQX_NAME=emqx
      - EMQX_HOST=node3.emqx.iot
      - EMQX_CLUSTER__DISCOVERY=static
      - EMQX_CLUSTER__STATIC__SEEDS=emqx@node1.emqx.iot,emqx@node2.emqx.iot,emqx@node3.emqx.iot,emqx@node4.emqx.iot
      - EMQX_LISTENER__TCP__INTERNAL=0.0.0.0:11883
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx_ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    networks:
      emqx-net:
        aliases:
          - node3.emqx.iot
  emqx4:
    image: emqx/emqx:${EMQX_VERSION}
    restart: always
    environment:
      - EMQX_NAME=emqx
      - EMQX_HOST=node4.emqx.iot
      - EMQX_CLUSTER__DISCOVERY=static
      - EMQX_CLUSTER__STATIC__SEEDS=emqx@node1.emqx.iot,emqx@node2.emqx.iot,emqx@node3.emqx.iot,emqx@node4.emqx.iot
      - EMQX_LISTENER__TCP__INTERNAL=0.0.0.0:11883
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx_ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    networks:
      emqx-net:
        aliases:
          - node4.emqx.iot
  # Haproxy
  haproxy:
    image: haproxy:${HAPROXY_VERSION}
    volumes: 
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks: 
      - emqx-net
    depends_on:
      - emqx1
      - emqx2
      - emqx3
      - emqx4
    ports:
      - ${EMQX_TCP_PORT}:1883
      - ${EMQX_INTERNAL_PORT}:11883
      - ${EMQX_DASHBOARD_PORT}:18083
      - ${HAPROXY_ADMIN_PORT}:8080

    

    
